server:
  port: 8080

# spring
spring:
  application:
    name: hstn
#  session:
#    store-type: redis
#    timeout: 60
  redis:
    port: 6379
    database: 1
    password: 123456

  # datasource
  datasource:
    # druid
    druid:
      url: jdbc:mysql://localhost:3306/heshituina_usermanage_pidu?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: 123456
# log
#logging:
#  level:
#    com.mozhumz.zuul.zuul-heshituina: info



#zuul
zuul:
  ignore-local-service: false
  sensitive-headers:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

#  ignored-patterns:
#    - '*'
  routes:

    hstn:
      path: /hstn/**
      serviceId: hstn
    usermanage:
      path: /usermanage/**
      serviceId: usermanage
    balance:
      path: /balance/**
      serviceId: balance

#hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000

#ribbon
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/
  instance:
    instance-id: zuul
    prefer-ip-address: true
#    ip-address: true
    metadata-map:
      zone: primary



